### ISSUE TITLE
obliczanie kubatura

### ISSUE THREAD

**Issue by mati2251** [mati2251/building-info#10]
Jako zarządca budynku mogę sprawdzić łączną kubaturę pomieszczeń w budynku, na poziomu czy też pobrać kubaturę pomieszczenia, aby móc prowadzić wyliczenia bazujące na kubaturze pomieszczeń

**Comment by DawidJedraszczyk** [comment]
merge request: [https://github.com/mati2251/building-info/pull/21](url)
