### ISSUE TITLE
Informacje o pomieszczeniach przekraczające wybrane progi

### ISSUE THREAD

**Issue by mati2251** [mati2251/building-info#13]
Jako zarządca budynku mogę otrzymać informację o pomieszczeniach w budynku, które przekraczają określony poziom zużycia energii cieplnej / m^3 podany jako parametr, aby znaleźć miejsca do poprawy w infrastrukturze.

**Comment by DawidJedraszczyk** [comment]
pull request: [https://github.com/mati2251/building-info/pull/22](url)
